version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql-edge
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: edge
      MYSQL_USER: edge_user
      MYSQL_PASSWORD: edgepass123

    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

  backend:
    env_file:
      - .env
    image: "${DOCKER_IMAGE_BACKEND:-my_app_backend2}:${TAG:-latest}"
    build:
      context: ./backend
      # dockerfile: Dockerfile.backend
    ports:
      - "8003:8003"
    command:
      [
        "uv",
        "run",
        "uvicorn",
        "main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8003",
        "--reload",
        "--reload-exclude",
        "logs/*",
      ]
    volumes:
      - ./backend:/app

  frontend:
    env_file:
      - .env
    image: "${DOCKER_IMAGE_FRONTEND:-my_app_frontend2}:${TAG:-latest}"
    build:
      context: ./frontend
    ports:
      - "80:8010"
    depends_on:
      - backend

volumes:
  mysql_data:
